### ISSUE TITLE
Feature Request: Convert Example to TypeScript

### ISSUE THREAD

**Issue by elliot-huffman** [Azure-Samples/ms-identity-node#11]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Clone Repo and run

### Any log messages given by the failure
> N/A

### Expected/desired behavior
> The code should be in TypeScript format to better describe the object structure, help avoid bugs, and accelerate app creation. This app can then be transpired to JS by the end user via the TSC command to get the JS equivalent in any ECMA Script version and any module import format based on the tsconfig. By having the app created in TypeScript, this allows for the flexibility to transpile the example code to any format that the end user sees fit without much maintainer work.

### OS and Version?
> All

### Versions
> All

**Comment by derisen** [comment]
@elliot-huffman apologies for the late response. This is a reasonable request, however with these quickstart samples the goal is to demonstrate a basic working app without much setup (which we use express generator for), as well as reach to widest audience. As a typescript sample, you could check [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/auth-code-pkce), and we have in backlog to create more samples using typescript. Hope this helps!

**Comment by elliot-huffman** [comment]
No worries, thanks for the heads up! I got it working on my side of things :-)
